version: 0.2

phases:
  build:
    commands:
      - echo "Creating deployment package..."
      - ls -l
      - zip -r deployment-package.zip .
artifacts:
  files:
    - deployment-package.zip
