version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Building Lambda package..."
      - pip install -r requirements.txt -t .
      - zip -r deployment-package.zip .
artifacts:
  files:
    - deployment-package.zip
