version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - echo "Checking for requirements.txt..."
      - if [ -f "requirements.txt" ]; then pip install -r requirements.txt -t .; else echo "No requirements.txt found, skipping package installation"; fi

  build:
    commands:
      - echo "Building the Lambda function..."
      - python -m py_compile lambda_function.py
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Creating deployment package..."
      - zip -r deployment-package.zip . -x "*.git*" "*.DS_Store" "buildspec.yml" "README.md" ".gitignore"

artifacts:
  files:
    - deployment-package.zip