version: 0.2

phases:
  build:
    commands:
      - echo "Creating deployment package..."
      - zip deployment-package.zip lambda_function.py

artifacts:
  files:
    - deployment-package.zip
