version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - if [ -f "requirements.txt" ]; then pip install -r requirements.txt -t .; else echo "No requirements.txt found"; fi

  build:
    commands:
      - echo "Building the Lambda function..."
      - python -m py_compile lambda_function.py
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Creating deployment package..."
      # Only include necessary files for Lambda
      - zip -r deployment-package.zip lambda_function.py
      - if [ -f "requirements.txt" ]; then zip -r deployment-package.zip . -x "*.git*" "*.DS_Store" "buildspec.yml" "README.md" ".gitignore"; fi

artifacts:
  files:
    - deployment-package.zip